@startuml

participant "TFTP Server" as server
participant "TFTP Client" as client

activate client
client -> server : Write Request
deactivate client
activate server
client <- server : Ack Block #0
deactivate server
activate client
client -> server : Send Block #1
deactivate client
activate server
client <- server : Ack Block #1
deactivate server
activate client
client -> server : Send Block #2
deactivate client
activate server
client <- server : Ack Block #2
deactivate server
activate client
...
client -> server : Send Block #n
note right: Less Data than \ndefined Block Size
deactivate client
activate server
client <- server : Ack Block #n
deactivate server



@enduml