@startuml

participant "wifi_send_udp_task" as Task

Task -> Queue : xQueueCreateStatic()
loop Polling
    Task -> Queue : xQueueReceive()
    alt If not connected
        Task -> Queue : break
    else If connected and command received
        alt Command is WIFI_TX_SEND_FRAME_REQUEST
            Task -> WiFi : wifi_send_packet()
            alt If send fails
                Task -> Queue : xQueueSend()
            end
        end
    end
end

@enduml