@startuml

hide time-axis
binary "A" as A
binary "B" as B
concise "Col Count" as CC
binary "Firepulse" as F

CC is "0"

@0
A is low

@1
A is high
CC is "1"
F is high
A -> B : Check
B -> CC: direction
@2
F is low
B is high
@3
A is low
@4
B is low

A is low
@5
A is high
CC is "2"
@6
B is high
@7
A is low
@8
B is low
@9
A is high
F is high
CC is "3"
@10
F is low
B is high
@11
A is low
@12
B is low

@enduml